# Generated by Django 3.2.13 on 2023-05-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TM_User', '0002_rename_name_user_tm_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_TM',
            new_name='Users',
        ),
    ]
