# Generated by Django 3.2.13 on 2023-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_User', '0003_rename_user_tm_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityName', models.TextField(max_length=255)),
                ('ExtenalCourseName', models.TextField(max_length=100)),
                ('ExternalCourseNumber', models.TextField(max_length=10)),
                ('SourceID', models.TextField(max_length=10)),
                ('SchoolSubject', models.TextField(max_length=100)),
                ('ExternalUnits', models.TextField(max_length=5)),
                ('TermType', models.TextField(max_length=15)),
                ('ExternalCourseDescription', models.TextField(max_length=255)),
                ('AccreditionStatus', models.TextField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='role',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='Username',
        ),
    ]
