# Generated by Django 3.2.13 on 2023-05-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_User', '0004_auto_20230511_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSUSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSUCourseName', models.TextField(max_length=100)),
                ('PSUCourseNumber', models.TextField(max_length=10)),
                ('PSUUnits', models.TextField(max_length=5)),
                ('PSUCourseCatalog', models.TextField(max_length=191)),
            ],
        ),
    ]
