# Generated by Django 3.2.13 on 2023-05-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TM_User', '0005_psusyllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsyllabus',
            name='ExternalUnits',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='psusyllabus',
            name='PSUUnits',
            field=models.IntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitsTaken', models.IntegerField()),
                ('PercentMatch', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ExternalID', models.ForeignKey(db_column='external_id', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='TM_User.externalsyllabus')),
                ('PSUID', models.ForeignKey(db_column='psu_id', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='TM_User.psusyllabus')),
            ],
        ),
    ]
