# Generated by Django 3.2.13 on 2023-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_User', '0006_auto_20230511_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='Match',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalsyllabus',
            name='ExternalUnits',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='psusyllabus',
            name='PSUUnits',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
